services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      - blogverse-net
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./DA-blogverse-backend
      dockerfile: Dockerfile
    # Le nom de l'image respecte ton DA
    image: dusly007/tp2-2395223-blogverse-backend:latest
    environment:
      DB_HOST: db
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: root
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - blogverse-net
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./DA-blogverse-frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
    image: dusly007/tp2-2395223-blogverse-frontend:latest
    networks:
      - blogverse-net
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  db_data:

networks:
  blogverse-net:
    driver: bridge